services:
  - name: chem-backend
    type: web
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: gunicorn backend.wsgi --bind 0.0.0.0:$PORT
